---
apiVersion: v1
kind: Namespace
metadata:
  name: app-ml-team
  labels:
    team: ml-engineering
    environment: local
    cost-center: ml
    workload-type: ml-training
    app.kubernetes.io/name: app-ml-team
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-data-team
  labels:
    team: data-engineering
    environment: local
    cost-center: data
    workload-type: data-processing
    app.kubernetes.io/name: app-data-team
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-core-team
  labels:
    team: app-engineering
    environment: local
    cost-center: app
    workload-type: application
    app.kubernetes.io/name: app-core-team
    app.kubernetes.io/component: namespace