apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-prod

resources:
  - ../../../base/gitops

patches:
  - path: argocd-prod-patches.yaml
    target:
      kind: ArgoCD
      name: argocd

labels:
  - pairs:
      app.kubernetes.io/part-of: gitops
      app.kubernetes.io/environment: prod
      app.kubernetes.io/managed-by: kustomize