apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - network-policies.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ml-platform
