---
# Security Policies Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-policies
  namespace: argocd
  labels:
    app.kubernetes.io/name: security-policies
    app.kubernetes.io/component: security
spec:
  project: default
  source:
    repoURL: https://github.com/gigifokchiman/implement-ml-p.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/security/policies
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# TLS Certificates Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-certificates
  namespace: argocd
  labels:
    app.kubernetes.io/name: tls-certificates
    app.kubernetes.io/component: security
spec:
  project: default
  source:
    repoURL: https://github.com/gigifokchiman/implement-ml-p.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/security/tls
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Team Namespaces Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-namespaces
  namespace: argocd
  labels:
    app.kubernetes.io/name: team-namespaces
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/gigifokchiman/implement-ml-p.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/team-isolation
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true