apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-operator-crds.yaml
  - service-monitors.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/part-of: ml-platform
