# Prometheus Operator CRDs for monitoring resources
# These are required for ServiceMonitor and PodMonitor resources
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-crds-info
  namespace: data-platform-monitoring
data:
  info: |
    Prometheus Operator CRDs are installed via install-prometheus-crds.sh script
    This includes:
    - ServiceMonitor CRD
    - PodMonitor CRD  
    - PrometheusRule CRD
    - Prometheus CRD
    - Alertmanager CRD