apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app-ml-platform/
  - app-data-platform/
  - network/
  - security/
  - storage/

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      project: ml-platform
