apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform

resources:
  - ../../base

patches:
  # Configure S3 bucket for development
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "ml-platform-dev-data-lake"

secretGenerator:
  # Development secrets
  - name: database-credentials
    literals:
      - url=postgresql://admin:$(DATABASE_PASSWORD)@ml-platform-dev-metadata.region.rds.amazonaws.com:5432/metadata
      - username=admin
      - password=$(DATABASE_PASSWORD)

labels:
  - includeSelectors: true
    pairs:
      environment: dev
      deployment-method: eks
