apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-processing-job
  labels:
    app.kubernetes.io/name: data-processor
    app.kubernetes.io/component: data-processing
    app.kubernetes.io/part-of: ml-platform
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM

  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: data-processor
        app.kubernetes.io/component: data-processing
        app.kubernetes.io/part-of: ml-platform

    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: data-processor
            app.kubernetes.io/component: data-processing
            app.kubernetes.io/part-of: ml-platform
        spec:
          serviceAccountName: ml-platform-data-worker
          priorityClassName: data-processing

          # Security context for pod
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 2000
            seccompProfile:
              type: RuntimeDefault

          # Schedule on data processing nodes
          nodeSelector:
            ml-platform/workload: data

          tolerations:
            - key: workload
              operator: Equal
              value: data
              effect: NoSchedule

          containers:
            - name: processor
              image: python:3.9-alpine

              # Security context for container
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
                capabilities:
                  drop:
                    - ALL

              command:
                - "/bin/sh"
                - "-c"
                - "echo 'Processing data...' && python -c 'import time; time.sleep(30); print(\"Data processing complete\")'"

              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: database-connection
                      key: url
                - name: DATA_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-connection
                      key: data_lake_bucket

              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"

          restartPolicy: OnFailure

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-platform-data-worker
  labels:
    app.kubernetes.io/name: data-processor
    app.kubernetes.io/component: data-processing
    app.kubernetes.io/part-of: ml-platform
