apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ml-platform-environments
  namespace: argocd
  labels:
    app.kubernetes.io/name: ml-platform-applicationset
    app.kubernetes.io/part-of: gitops
spec:
  generators:
    # Git directory generator - discovers environments automatically
    - git:
        repoURL: https://github.com/gigifokchiman/implement-ml-p  # Update with actual repo
        revision: HEAD
        directories:
          - path: infrastructure/kubernetes/overlays/*
          - path: infrastructure/kubernetes/overlays/local
          - path: infrastructure/kubernetes/overlays/dev
          - path: infrastructure/kubernetes/overlays/staging
          - path: infrastructure/kubernetes/overlays/prod
        requeueAfterSeconds: 60

  template:
    metadata:
      name: 'ml-platform-{{path.basename}}'
      labels:
        environment: '{{path.basename}}'
        app.kubernetes.io/part-of: gitops
        managed-by: applicationset
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: ml-platform
      source:
        repoURL: https://github.com/gigifokchiman/implement-ml-p  # Update with actual repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: ml-platform
      syncPolicy:
        automated:
          prune: true  # Simplified for now
          selfHeal: true  # Simplified for now
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10

      # Environment-specific ignore differences
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: ""
          kind: Secret
          jsonPointers:
            - /data

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ml-platform-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: ml-platform-infrastructure-applicationset
    app.kubernetes.io/part-of: gitops
spec:
  generators:
    # List generator for infrastructure components
    - list:
        elements:
          - component: monitoring
            namespace: monitoring
            path: infrastructure/kubernetes/base/monitoring
            syncWave: "1"
          - component: security
            namespace: security
            path: infrastructure/kubernetes/base/security
            syncWave: "1"
          - component: storage
            namespace: storage
            path: infrastructure/kubernetes/base/storage
            syncWave: "0"

  template:
    metadata:
      name: 'infrastructure-{{component}}'
      labels:
        component: '{{component}}'
        app.kubernetes.io/part-of: gitops
        type: infrastructure
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: ml-platform-infrastructure
      source:
        repoURL: https://github.com/gigifokchiman/implement-ml-p  # Update with actual repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # For CRDs
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
      revisionHistoryLimit: 10

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: ""
          kind: ConfigMap
          jsonPointers:
            - /data

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ml-platform-feature-branches
  namespace: argocd
  labels:
    app.kubernetes.io/name: ml-platform-feature-branches
    app.kubernetes.io/part-of: gitops
spec:
  generators:
    # Pull request generator for feature branch deployments
    - pullRequest:
        github:
          owner: your-org  # Update with actual GitHub org
          repo: ml-platform  # Update with actual repo name
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - preview  # Only PRs with 'preview' label
        requeueAfterSeconds: 300

  template:
    metadata:
      name: 'ml-platform-pr-{{number}}'
      labels:
        app.kubernetes.io/part-of: gitops
        type: preview
        pr-number: '{{number}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
        link.argocd.argoproj.io/external-link: '{{url}}'
    spec:
      project: ml-platform
      source:
        repoURL: https://github.com/gigifokchiman/implement-ml-p  # Update with actual repo
        targetRevision: '{{head_sha}}'
        path: infrastructure/kubernetes/overlays/local  # Use local config for previews
        kustomize:
          namePrefix: 'pr-{{number}}-'
          commonLabels:
            preview/pr-number: '{{number}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ml-platform-pr-{{number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false  # Manual healing for previews
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
      revisionHistoryLimit: 3  # Limited history for previews

      # Preview environments are ephemeral
      info:
        - name: 'Pull Request'
          value: '#{{number}}: {{title}}'
        - name: 'Author'
          value: '{{head_commit.author.name}}'
        - name: 'URL'
          value: '{{url}}'
