---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-ml-platform-sa
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-ml-platform-sa
    app.kubernetes.io/part-of: gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-ml-platform-role
  labels:
    app.kubernetes.io/name: argocd-ml-platform-role
    app.kubernetes.io/part-of: gitops
rules:
  # Core ML Platform resources
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "apps" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "extensions" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "policy" ]
    resources: [ "*" ]
    verbs: [ "*" ]

  # Monitoring resources
  - apiGroups: [ "monitoring.coreos.com" ]
    resources: [ "*" ]
    verbs: [ "*" ]

  # Storage resources
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "*" ]
    verbs: [ "*" ]

  # Custom resources for ML Platform
  - apiGroups: [ "kubeflow.org" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "argoproj.io" ]
    resources: [ "applications", "appprojects" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

  # Batch resources for ML jobs
  - apiGroups: [ "batch" ]
    resources: [ "*" ]
    verbs: [ "*" ]

  # Metrics and autoscaling
  - apiGroups: [ "autoscaling" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "*" ]
    verbs: [ "get", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-ml-platform-binding
  labels:
    app.kubernetes.io/name: argocd-ml-platform-binding
    app.kubernetes.io/part-of: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-ml-platform-role
subjects:
  - kind: ServiceAccount
    name: argocd-ml-platform-sa
    namespace: argocd
---
# Additional RBAC for namespace management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-namespace-manager
  labels:
    app.kubernetes.io/name: argocd-namespace-manager
    app.kubernetes.io/part-of: gitops
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "resourcequotas", "limitranges" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-namespace-manager-binding
  labels:
    app.kubernetes.io/name: argocd-namespace-manager-binding
    app.kubernetes.io/part-of: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-namespace-manager
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
