# Application Level Security Policies
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-headers
  namespace: app-ml-team
  labels:
    app.kubernetes.io/name: security-headers
    app.kubernetes.io/component: security
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        
        # Remove server tokens
        server_tokens off;
        
        # Disable unused methods
        if ($request_method !~ ^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$ ) {
            return 405;
        }
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req zone=api burst=20 nodelay;
        
        # Request size limiting
        client_max_body_size 10M;
        
        location / {
            proxy_pass http://app-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout settings
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-headers
  namespace: app-data-team
  labels:
    app.kubernetes.io/name: security-headers
    app.kubernetes.io/component: security
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        
        # Remove server tokens
        server_tokens off;
        
        # Disable unused methods
        if ($request_method !~ ^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$ ) {
            return 405;
        }
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=15r/s;
        limit_req zone=api burst=25 nodelay;
        
        # Request size limiting
        client_max_body_size 50M;
        
        location / {
            proxy_pass http://app-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout settings
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-headers
  namespace: app-core-team
  labels:
    app.kubernetes.io/name: security-headers
    app.kubernetes.io/component: security
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        
        # Remove server tokens
        server_tokens off;
        
        # Disable unused methods
        if ($request_method !~ ^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$ ) {
            return 405;
        }
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=20r/s;
        limit_req zone=api burst=30 nodelay;
        
        # Request size limiting
        client_max_body_size 25M;
        
        location / {
            proxy_pass http://app-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout settings
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }