apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policies.yaml
  - rate-limiting.yaml
  - app-level-security.yaml
  - resource-quotas.yaml
  - cluster-roles.yaml
  - rbac-bindings.yaml
  - limit-ranges.yaml

commonLabels:
  app.kubernetes.io/component: security
  app.kubernetes.io/managed-by: argocd