apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-local

resources:
- ../../../base/gitops

# Local environment customizations

# Local ingress configuration
patches:
- patch: |-
    - op: replace
      path: /spec/server/ingress/enabled
      value: true
    - op: replace
      path: /spec/server/config/url
      value: https://argocd.ml-platform.local
    - op: replace
      path: /spec/ha/enabled
      value: false
  target:
    group: argoproj.io
    kind: ArgoCD
    name: argocd
    version: v1beta1
- path: argocd-local-patches.yaml

# Configure for local development
configMapGenerator:
- behavior: create
  literals:
  - server.insecure=true
  - server.disable.auth=false
  - application.instanceLabelKey=argocd.argoproj.io/instance
  name: argocd-cmd-params-cm

labels:
- pairs:
    deployment-method: argocd
    environment: local
