version: '3.8'

services:
  infra-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: ml-platform/infra-tools:latest
    container_name: ml-platform-infra-tools
    working_dir: /workspace
    volumes:
      # Mount the entire infrastructure directory
      - .:/workspace
      # Mount Docker socket for Kind and Docker commands
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount local .kube directory
      - ~/.kube:/workspace/.kube:ro
      # Mount AWS credentials if they exist
      - ~/.aws:/workspace/.aws:ro
      # Mount SSH keys for Git operations
      - ~/.ssh:/workspace/.ssh:ro
      # Cache directories for faster rebuilds
      - terraform-cache:/workspace/.terraform.d
      - helm-cache:/workspace/.cache/helm
    environment:
      # Terraform configuration
      - TF_LOG=INFO
      - TF_LOG_PATH=/workspace/terraform.log
      - TF_IN_AUTOMATION=1
      - TF_INPUT=0

      # Kubernetes configuration
      - KUBECONFIG=/workspace/.kube/config
      - KUBE_CONFIG_PATH=/workspace/.kube/config

      # AWS configuration
      - AWS_PROFILE=default
      - AWS_DEFAULT_REGION=us-west-2

      # Tool configurations
      - HELM_CACHE_HOME=/workspace/.cache/helm
      - HELM_CONFIG_HOME=/workspace/.config/helm
      - CHECKOV_LOG_LEVEL=INFO

      # Development settings
      - TERM=xterm-256color
      - COLORTERM=truecolor
    networks:
      - infra-network
    tty: true
    stdin_open: true
    restart: unless-stopped

    # Health check to ensure all tools are working
    healthcheck:
      test: [ "/usr/local/bin/health-check.sh" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Documentation server for infrastructure docs
  docs:
    image: nginx:alpine
    container_name: ml-platform-infra-docs
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - infra-network
    restart: unless-stopped
    profiles:
      - docs

volumes:
  terraform-cache:
    driver: local
  helm-cache:
    driver: local

networks:
  infra-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
