apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-dev

resources:
  - ../../../base/gitops

patches:
  - path: argocd-dev-patches.yaml
    target:
      kind: ArgoCD
      name: argocd

labels:
  - pairs:
      app.kubernetes.io/part-of: gitops
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: kustomize