apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
  labels:
    app.kubernetes.io/name: data-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: data-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: data-api
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: data-platform
    spec:
      containers:
        - name: data-api
          image: data-platform/data-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: data-platform-config
                  key: LOG_LEVEL
            - name: METRICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: data-platform-config
                  key: METRICS_ENABLED
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: data-platform-database-connection
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: data-platform-redis-connection
                  key: url
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: data-platform-s3-connection
                  key: endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: data-platform-s3-connection
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: data-platform-s3-connection
                  key: secret_key
            - name: RAW_DATA_BUCKET
              valueFrom:
                secretKeyRef:
                  name: data-platform-s3-connection
                  key: raw_data_bucket
            - name: PROCESSED_DATA_BUCKET
              valueFrom:
                secretKeyRef:
                  name: data-platform-s3-connection
                  key: processed_data_bucket
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: data-api
  labels:
    app.kubernetes.io/name: data-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: data-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: data-api
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
