apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-quality-checker
  labels:
    app.kubernetes.io/name: data-quality-checker
    app.kubernetes.io/component: quality
    app.kubernetes.io/part-of: data-platform
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: data-quality-checker
            app.kubernetes.io/component: quality
            app.kubernetes.io/part-of: data-platform
        spec:
          restartPolicy: OnFailure
          containers:
            - name: data-quality-checker
              image: data-platform/data-quality:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: LOG_LEVEL
                  valueFrom:
                    configMapKeyRef:
                      name: data-platform-config
                      key: LOG_LEVEL
                - name: DATA_QUALITY_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: data-platform-config
                      key: DATA_QUALITY_ENABLED
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: data-platform-database-connection
                      key: url
                - name: S3_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: data-platform-s3-connection
                      key: endpoint
                - name: S3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: data-platform-s3-connection
                      key: access_key
                - name: S3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: data-platform-s3-connection
                      key: secret_key
                - name: RAW_DATA_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: data-platform-s3-connection
                      key: raw_data_bucket
                - name: PROCESSED_DATA_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: data-platform-s3-connection
                      key: processed_data_bucket
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "2000m"
