apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-applications

resources:
  - ml-platform-local.yaml
  - ml-platform-dev.yaml
  - ml-platform-staging.yaml
  - ml-platform-prod.yaml
  - data-platform-local.yaml
  - monitoring.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: gitops
      app.kubernetes.io/component: applications
      app.kubernetes.io/managed-by: kustomize