apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-platform-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: ml-platform-dev
    app.kubernetes.io/part-of: gitops
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ml-platform

  source:
    repoURL: https://github.com/gigifokchiman/implement-ml-p  # Update with actual repo
    targetRevision: HEAD
    path: infrastructure/kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: ml-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Allow HPA to manage replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data

  info:
    - name: 'Environment'
      value: 'Development'
    - name: 'URL'
      value: 'https://ml-platform-dev.aws.com'
