apiVersion: v2
name: platform-template
description: A Helm chart template for creating new application platforms
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: database.enabled
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: cache.enabled
  - name: minio
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    condition: storage.enabled
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled

maintainers:
  - name: ML Platform Team
    email: ml-platform@company.com

keywords:
  - platform
  - microservices
  - kubernetes
  - database
  - cache
  - storage
  - monitoring