# Generated terraform configuration for staging environment
# DO NOT EDIT MANUALLY - Generated by generate-terraform-versions.sh
# Source: terraform/versions/terraform-versions.yaml

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.95.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "= 2.24.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "= 2.12.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "= 3.6.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "= 3.2.2"
    }
    time = {
      source  = "hashicorp/time"
      version = "= 0.10.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "= 4.0.5"
    }
    local = {
      source  = "hashicorp/local"
      version = "= 2.4.1"
    }
    external = {
      source  = "hashicorp/external"
      version = "= 2.3.2"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "= 2.4.1"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "= 2.3.3"
    }
  }

  # Uncomment for remote state
  # backend "s3" {
  #   bucket = "your-terraform-state-bucket"
  #   key    = "staging/terraform.tfstate"
  #   region = "us-west-2"
  # }
}
