apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ml-platform-local

resources:
  - ../../base

namespace: ml-platform

configMapGenerator:
  - name: ml-platform-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=local

secretGenerator:
  - name: database-connection
    behavior: replace
    literals:
      - url=postgresql://admin:changeme123@postgresql.ml-platform.svc.cluster.local:5432/metadata
  - name: s3-connection
    behavior: replace
    literals:
      - endpoint=http://minio.ml-platform.svc.cluster.local:9000
      - access_key=minioadmin
      - secret_key=changeme123

labels:
  - pairs:
      environment: local
    includeSelectors: false
