---
# MinIO Object Storage for Data Lake
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: ml-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
automountServiceAccountToken: false
---
# Secret for MinIO credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: ml-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
type: Opaque
data:
  # admin/changeme123 (base64 encoded)
  root-user: "YWRtaW4="
  root-password: "Y2hhbmdlbWUxMjM="
---
# PersistentVolumeClaim for MinIO data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: ml-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  # Storage class will be overridden by environment overlays
  storageClassName: "gp2"
---
# Service for MinIO
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ml-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
---
# Deployment for MinIO
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: ml-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: storage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: storage
    spec:
      serviceAccountName: minio
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: minio
          image: bitnami/minio:2024.8.17
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
            - name: MINIO_API_PORT_NUMBER
              value: "9000"
            - name: MINIO_CONSOLE_PORT_NUMBER
              value: "9001"
            - name: MINIO_DATA_DIR
              value: "/data"
            - name: MINIO_BROWSER
              value: "on"
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
        - name: tmp
          emptyDir: { }
