# Registry resources are now in the ml-platform namespace
# Namespace is managed by the base configuration
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: ml-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: ml-platform
type: Opaque
data:
  # Default: admin:admin123
  htpasswd: YWRtaW46JDJ5JDA1JFJmLkxDT09XdDhUZTlLSGNSQmVmSi5KT3pJT0VyNmNlVVNtVnBZTVFoSEFPMVB5dnVDbkNl
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: ml-platform
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: ML Platform Registry
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: ml-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
              name: registry
              protocol: TCP
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: registry-auth
              mountPath: /auth
              readOnly: true
            - name: registry-config
              mountPath: /etc/docker/registry
              readOnly: true
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: registry-auth
          secret:
            secretName: registry-auth
            items:
              - key: htpasswd
                path: htpasswd
        - name: registry-config
          configMap:
            name: registry-config
            items:
              - key: config.yml
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: ml-platform
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
      name: registry
  selector:
    app: docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-internal
  namespace: ml-platform
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registry
  selector:
    app: docker-registry
